class CreateEndEntities < ActiveRecord::Migration
  def change
    create_table :end_entities do |t|
      t.references :app
      t.string :uuid                      # UUID autogenerated for this device - added as a OU value in the EE cert
      t.string :e_password                # Password for the ejbca end entity user record
      t.string :did                       # Device Identifier - user specified unique name for a device - added as a OU value in the EE cert
      t.string :slug                      # Friendly name
      t.integer :status, default: 0       # 0 => new, 1 => pending, 2 => enrolled, 4 => revoked

      t.timestamps
    end
  end
end
